name: CI for ssh-mapper
on: [push, pull_request]

jobs:
  ssh-mapper-dropbear-server:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ready SSH keys
        run: experiments/scripts/make_ssh_keys.sh

      - name: Start learning DropbearSSH server
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          up-flags: "--build -d"

      - name: Verify Result
        run: |
          experiments/scripts/diff_hyps.sh experiments/results/servers/dropbear ./learner_output 3
