name: CI for ssh-mapper
on: [push, pull_request]

jobs:
  ssh-mapper-dropbear-server:
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start learning DropbearSSH server
        run: cd experiments/scripts/ && bash start_experiment.sh dropbear
        # uses: hoverkraft-tech/compose-action@v2.0.1
        # with:
        #   compose-file: "./docker-compose.yaml"
        #   up-flags: "--build"

      - name: Verify Result
        run: |
          # wait for the learning to be over
          while [ "$( docker container inspect -f '{{.State.Running}}' dropbear-learner )" = "true" ]; do date; echo "still learning"; sleep 5; done
          experiments/scripts/diff_hyps.sh experiments/results/servers/dropbear experiments/orchestration/learner_output_dropbear 3
